[package]
name = "cmd_lib"
description = "Common rust commandline macros and utils, to write shell script like tasks easily"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rust-shell-script/rust_cmd_lib"
repository = "https://github.com/rust-shell-script/rust_cmd_lib"
documentation = "https://docs.rs/cmd_lib"
keywords = ["shell", "scripts", "commandline", "subprocess", "pipeline"]
categories = ["command-line-interface", "command-line-utilities"]
readme = "README.md"
version = "0.12.1"
authors = ["rust-shell-script <rust-shell-script@gmail.com>"]
edition = "2018"

[workspace]
members = ["macros", "examples"]

[dependencies]
cmd_lib_macros = { version = "0.12.1", path = "./macros" }

[dev-dependencies]
rayon = "1.5"
clap = "2.33"
