[package]
name = "cmd_lib"
description = "Common rust commandline macros and utils, to write shell script like tasks easily"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rust-shell-script/rust_cmd_lib"
repository = "https://github.com/rust-shell-script/rust_cmd_lib"
documentation = "https://docs.rs/cmd_lib"
keywords = ["shell", "scripts", "commandline", "subprocess", "pipeline"]
categories = ["command-line-interface", "command-line-utilities"]
readme = "README.md"
version = "0.8.5"
authors = ["rust-shell-script <rust-shell-script@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "crates/proc_macros",
  "crates/cmd_lib_core",
]

[dependencies]
cmd_lib_core = { path = "crates/cmd_lib_core" }
cmd_lib_macros = { path = "crates/proc_macros" }

